/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-regenerated by `next dev`/`next build` -- committed here
// only so tsconfig.json's `include` doesn't point at a missing file before
// the first build runs. See https://nextjs.org/docs/app/api-reference/config/typescript
