import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = join(__dirname, "..");
const component = readFileSync(join(ROOT, "components", "section-mark.tsx"), "utf8");
const script = readFileSync(join(ROOT, "scripts", "build-tab-marks.mjs"), "utf8");

// The two marks that are not drops are committed static art, generated by scripts/build-tab-marks.mjs
// and drawn in the same 46px box as the catalog's own icons. Nothing at build or CI time regenerates
// them, so nothing else would notice a missing file or one that came back the wrong size: the tab
// would just quietly lose its mark, which is how the first attempt shipped an unreadable one.
const CANVAS = 46;

/** Width and height out of a PNG's IHDR, which is enough to check the canvas without a decoder. */
function pngSize(path: string): { width: number; height: number } {
  const buf = readFileSync(path);
  expect(buf.subarray(1, 4).toString("ascii"), `${path} is not a PNG`).toBe("PNG");
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

describe("the tab marks that are not drops", () => {
  const paths = [...component.matchAll(/"(\/marks\/[\w-]+\.png)"/g)].map((m) => m[1]!);

  it("names at least one", () => {
    expect(paths.length).toBeGreaterThan(0);
  });

  it.each(paths)("ships %s, on the same canvas the drop icons use", (p) => {
    const file = join(ROOT, "public", p);
    expect(existsSync(file), `${p} is referenced but not committed. Run \`pnpm marks\`.`).toBe(
      true,
    );
    expect(pngSize(file)).toEqual({ width: CANVAS, height: CANVAS });
  });

  it("has a generator that can produce every one of them again", () => {
    for (const p of paths) {
      const key = p.replace("/marks/", "").replace(".png", "");
      expect(script, `${key} is drawn but build-tab-marks.mjs would not rebuild it`).toContain(
        `"${key}"`,
      );
    }
  });

  // The generator centres art on a 46px canvas the way catalog/build.py does. If build.py's numbers
  // move, these were normalised to the old ones and will sit at a different size to the drop beside
  // them, which nothing else would catch.
  it("normalises to the same numbers catalog/build.py does", () => {
    const py = readFileSync(join(ROOT, "..", "catalog", "build.py"), "utf8");
    for (const name of ["ICON_CANVAS", "ICON_CONTENT", "ICON_VERSION"]) {
      const theirs = new RegExp(`^${name} = (\\d+)`, "m").exec(py)?.[1];
      const ours = new RegExp(`const ${name} = (\\d+)`).exec(script)?.[1];
      expect(theirs, `${name} not found in catalog/build.py`).toBeDefined();
      expect(ours, `${name} not found in build-tab-marks.mjs`).toBe(theirs);
    }
  });
});
