import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = join(__dirname, "..");
const component = readFileSync(join(ROOT, "components", "section-mark.tsx"), "utf8");
const script = readFileSync(join(ROOT, "scripts", "build-tab-marks.mjs"), "utf8");
const css = readFileSync(join(ROOT, "app", "globals.css"), "utf8");

// The tab marks are committed static art, generated by scripts/build-tab-marks.mjs. Nothing at build
// or CI time regenerates them, so nothing else would notice a missing file, one that came back the
// wrong size, or a box that stopped matching the canvas. That last one is not hypothetical: they
// shipped on a 46px canvas drawn into a 23px box, and the halving made one of them unreadable.
const CANVAS = Number(/const MARK_CANVAS = (\d+)/.exec(script)![1]!);

/** Width and height out of a PNG's IHDR, which is enough to check the canvas without a decoder. */
function pngSize(path: string): { width: number; height: number } {
  const buf = readFileSync(path);
  expect(buf.subarray(1, 4).toString("ascii"), `${path} is not a PNG`).toBe("PNG");
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

describe("the Drop Log tab marks", () => {
  const paths = [...component.matchAll(/"(\/marks\/[\w-]+\.png)"/g)].map((m) => m[1]!);

  it("names some", () => {
    expect(paths.length).toBeGreaterThan(0);
  });

  it.each(paths)("ships %s at the canvas the script builds", (p) => {
    const file = join(ROOT, "public", p);
    expect(existsSync(file), `${p} is referenced but not committed. Run \`pnpm marks\`.`).toBe(
      true,
    );
    expect(pngSize(file)).toEqual({ width: CANVAS, height: CANVAS });
  });

  it("has a generator that can produce every one of them again", () => {
    for (const p of paths) {
      const key = p.replace("/marks/", "").replace(".png", "");
      expect(script, `${key} is drawn but build-tab-marks.mjs would not rebuild it`).toContain(
        `"${key}"`,
      );
    }
  });

  // Drawn at anything other than the canvas size, pixel art is either mush or a fraction of what it
  // should be. This is the rule pixel-scaling-css.test.ts keeps for every other sprite; .tab-art is
  // in that table too, and this pins the OTHER end of it, the canvas the files are actually built at.
  it("draws them 1:1, at exactly the canvas size", () => {
    const rule = /\.tab-art \{([^}]*)\}/.exec(css);
    expect(rule, "no .tab-art rule in globals.css").not.toBeNull();
    const width = /width:\s*(\d+)px/.exec(rule![1]!)?.[1];
    const height = /height:\s*(\d+)px/.exec(rule![1]!)?.[1];
    expect(Number(width), `.tab-art is ${width}px but the marks are ${CANVAS}px`).toBe(CANVAS);
    expect(height).toBe(width);
  });

  // The dataset is shared with the catalog: a mark and the same item's catalog icon must not come
  // from two different extractions. The canvas is deliberately NOT shared, which is the whole point
  // of this file existing, so only the version is checked.
  it("fetches from the same pinned dataset catalog/build.py does", () => {
    const py = readFileSync(join(ROOT, "..", "catalog", "build.py"), "utf8");
    const theirs = /^ICON_VERSION = (\d+)/m.exec(py)?.[1];
    const ours = /const ICON_VERSION = (\d+)/.exec(script)?.[1];
    expect(theirs, "ICON_VERSION not found in catalog/build.py").toBeDefined();
    expect(ours).toBe(theirs);
  });

  // A mark that is also a catalog drop takes its id out of drops.yaml, so the two cannot name
  // different sprites. Read the key from the script rather than naming it here, or this becomes a
  // second place to edit whenever the drop changes, which is the drift it exists to prevent.
  it("takes a drop mark's sprite id from the catalog rather than repeating it", () => {
    const keys = [...script.matchAll(/fromCatalog: "([\w-]+)"/g)].map((m) => m[1]!);
    expect(keys.length, "no mark reads its id from the catalog").toBeGreaterThan(0);
    const yaml = readFileSync(join(ROOT, "..", "catalog", "drops.yaml"), "utf8");
    for (const key of keys) {
      expect(
        yaml,
        `build-tab-marks.mjs asks the catalog for ${key}, which drops.yaml has no icon_id for`,
      ).toMatch(new RegExp(`- key: ${key}\\n(?:\\s+\\w+:.*\\n)*?\\s+icon_id: \\d+`));
    }
  });

  // Scaling is the failure this whole file guards. It has shipped twice: a 46px canvas drawn into a
  // 23px box, then a 32px canvas holding art that is 34px. The generator refuses to resize at all
  // now, so a sprite that does not fit is an error rather than a quietly softened mark.
  it("has a generator that refuses to scale rather than shrinking art to fit", () => {
    expect(
      script,
      "build-tab-marks.mjs resizes again; art must fit the canvas or fail",
    ).not.toMatch(/\.resize\(|lanczos/);
    expect(script).toMatch(/larger than MARK_CANVAS/);
  });
});
